run/tests: Move to a dir based approach to scale easier
Before we generated the test data in the test script, but this made it hard
to include new test data.

By moving to a directory based approach we can easily copy n paste /etc/ dirs
from real environments and test them.
With the tradeoff to make it slightly more difficult to manage by hand, and having
more files.

Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

diff --git a/virt-v2v/pkg/customize/scripts/rhel/run/network_config_util_test b/virt-v2v/pkg/customize/scripts/rhel/run/network_config_util_test
--- a/virt-v2v/pkg/customize/scripts/rhel/run/network_config_util_test
+++ b/virt-v2v/pkg/customize/scripts/rhel/run/network_config_util_test
@@ -2,84 +2,68 @@
 
 SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
 
-# Temporary directory for testing
-TEST_DIR=$(mktemp -d)
+PASS() { echo "PASS: $@" ; }
+FAIL() { echo "FAIL: $@" ; }
+
+test_in_dir() {
+export TEST_DIR=$(mktemp -d --suffix="-forklift")
 
 # Paths for the test
-export V2V_MAP_FILE="$TEST_DIR/macToIP"
-export NETWORK_SCRIPTS_DIR="$TEST_DIR/network-scripts"
-export NETWORK_CONNECTIONS_DIR="$TEST_DIR/system-connections"
-export UDEV_RULES_FILE="$TEST_DIR/70-persistent-net.rules"
-export NETPLAN_DIR="$TEST_DIR"
+export V2V_MAP_FILE="$TEST_DIR/tmp/macToIP"
+export NETWORK_SCRIPTS_DIR="$TEST_DIR/etc/sysconfig/network-scripts"
+export NETWORK_CONNECTIONS_DIR="$TEST_DIR/etc/NetworkManager/system-connections"
+export UDEV_RULES_FILE="$TEST_DIR/etc/udev/rules.d/70-persistent-net.rules"
+export NETPLAN_DIR="$TEST_DIR/etc/netplan"
+
+    export TEST_SRC_DIR=$1  #${SCRIPT_DIR}/ifcfg-test.d
+    export EXPECTED_UDEV_RULE_FILE="$TEST_SRC_DIR/expected-udev.rule"
+
+    echo "Testing: $1"
+
+    cp -a $TEST_SRC_DIR/root/* $TEST_DIR
+
+    # Clean up from previous runs
+    rm -f "$UDEV_RULES_FILE"
+    mkdir -p $(dirname "$UDEV_RULES_FILE")
+
+    # Source the script under test
+    {
+    . ${SCRIPT_DIR}/network_config_util.sh
+    } > $TEST_DIR/main.log 2>&1
+
+    # Test 1: Verify the udev rules file was created
+    if [ ! -f "$UDEV_RULES_FILE" ]; then
+        echo "Test 1 Failed: UDEV_RULES_FILE not created."
+        exit 1
+    fi
+
+    if ! cmp -s $EXPECTED_UDEV_RULE_FILE $UDEV_RULES_FILE ; then
+        echo "Test 2 Failed: The content of $UDEV_RULES_FILE does not match the expected rule."
+        tail $UDEV_RULES_FILE
+        diff -u $EXPECTED_UDEV_RULE_FILE $UDEV_RULES_FILE
+        exit 1
+    fi
+
+    PASS $TEST_SRC_DIR
+}
+
+test_glob_dirs() {
+    for THE_DIR in $@;
+    do
+        test_in_dir "$THE_DIR"
+    done
+}
+
 
 # Test systems using network-scripts
 # ----------------------------------
-
-# Clean up from previous runs
-rm -f "$UDEV_RULES_FILE"
-rm -rf "$NETWORK_SCRIPTS_DIR" "$NETWORK_CONNECTIONS_DIR" "$NETPLAN_DIR"
-mkdir -p "$NETWORK_SCRIPTS_DIR"
-
-# Create mock data
-printf "aa:bb:cc:dd:ee:ff:ip:192.168.1.10,things,more\naa:bb:cc:dd:ee:fe:ip:192.168.1.11,hello,world\naa:bb:cc:dd:ee:fd:ip:2001:0db8:85a3:0000:0000:8a2e:0370:7334\n" > "$V2V_MAP_FILE"
-printf "DEVICE=\"eth0\"\nIPADDR=192.168.1.10\n" > "$NETWORK_SCRIPTS_DIR/ifcfg-eth0"
-
-# Source the script under test
-. ${SCRIPT_DIR}/network_config_util.sh
-
-# Run the script
-main
-
-printf "\nTest network config output:\n"
-echo "FILE_START"
-cat $UDEV_RULES_FILE
-echo "FILE_END"
-
-# Test 1: Verify the udev rules file was created
-if [ ! -f "$UDEV_RULES_FILE" ]; then
-    echo "Test 1 Failed: UDEV_RULES_FILE not created."
-    exit 1
-fi
-
-# Test 2: Verify the content of the udev rules file
-EXPECTED_RULE="SUBSYSTEM==\"net\",ACTION==\"add\",ATTR{address}==\"aa:bb:cc:dd:ee:ff\",NAME=\"eth0\""
-if ! echo "$EXPECTED_RULE" | cmp -s - "$UDEV_RULES_FILE"; then
-    echo "Test 2 Failed: The content of $UDEV_RULES_FILE does not match the expected rule."
-    exit 1
-fi
+test_glob_dirs ${SCRIPT_DIR}/ifcfg-*-test.d;
 
 # Test systems using system-connections
 # -------------------------------------
+test_glob_dirs ${SCRIPT_DIR}/networkmanager*-test.d;
 
-# Clean up from previous runs
-rm -f "$UDEV_RULES_FILE"
-rm -rf "$NETWORK_SCRIPTS_DIR" "$NETWORK_CONNECTIONS_DIR" "$NETPLAN_DIR"
-mkdir -p "$NETWORK_CONNECTIONS_DIR"
-
-# Create mock data
-printf "aa:bb:cc:dd:ee:ff:ip:192.168.1.10,things,more\naa:bb:cc:dd:ee:fe:ip:192.168.1.11,hello,world\naa:bb:cc:dd:ee:fd:ip:2001:0db8:85a3:0000:0000:8a2e:0370:7334\n" > "$V2V_MAP_FILE"
-printf "[connection]\ninterface-name=eth3\naddress1=192.168.1.11/24\n" > "$NETWORK_CONNECTIONS_DIR/eth1 but with spaces.nmconnection"
-
-# Run the script
-main
-
-printf "\nTest network connection output:\n"
-echo "FILE_START"
-cat $UDEV_RULES_FILE
-echo "FILE_END"
-
-# Test 1: Verify the udev rules file was created
-if [ ! -f "$UDEV_RULES_FILE" ]; then
-    echo "Test 1 Failed: UDEV_RULES_FILE not created."
-    exit 1
-fi
-
-# Test 1: Verify the content of the udev rules file
-EXPECTED_RULE="SUBSYSTEM==\"net\",ACTION==\"add\",ATTR{address}==\"aa:bb:cc:dd:ee:fe\",NAME=\"eth3\""
-if ! echo "$EXPECTED_RULE" | cmp -s - "$UDEV_RULES_FILE"; then
-    echo "Test 2 Failed: The content of $UDEV_RULES_FILE does not match the expected rule."
-    exit 1
-fi
+exit 0
 
 # Test systems using netplan YAML
 # -------------------------------
